import { mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import Domain from '../models/Domain';
import { DomainTarget } from '@quantum/contracts/modules/domain/domain';
import { config } from '@/shared/config';
import { logger } from '@/shared/utils/Logger';

const FILE_NAME = 'upstreams.yml';

const routerName = (domainId: number): string => `upstream-${domainId}`;

const quote = (value: string): string => JSON.stringify(value);

export const isRuleSafeHost = (host: string): boolean => /^[a-z0-9*.-]+$/i.test(host);

interface UpstreamRoute{
    id: number;
    host: string;
    upstreamUrl: string;
    tls: boolean;
}

const MIDDLEWARE = [
    '  middlewares:',
    '    to-https:',
    '      redirectScheme:',
    '        scheme: https',
    '        permanent: true',
    '    strip-api:',
    '      stripPrefix:',
    '        prefixes: ["/api"]'
].join('\n');

export const renderUpstreamConfig = (routes: UpstreamRoute[]): string => {
    const routers: string[] = [];
    const services: string[] = [];

    for(const route of routes){
        const name = routerName(route.id);

        routers.push([
            `    ${name}:`,
            `      rule: ${quote(`Host(\`${route.host}\`)`)}`,
            `      entryPoints: [${route.tls ? 'websecure' : 'web'}]`,
            `      service: ${name}`,
            ...(route.tls ? ['      tls:', '        certResolver: le'] : [])
        ].join('\n'));

        if(route.tls){
            routers.push([
                `    ${name}-plain:`,
                `      rule: ${quote(`Host(\`${route.host}\`)`)}`,
                '      entryPoints: [web]',
                `      service: ${name}`,
                '      middlewares: [to-https]'
            ].join('\n'));
        }

        services.push([
            `    ${name}:`,
            '      loadBalancer:',
            '        servers:',
            `          - url: ${quote(route.upstreamUrl)}`
        ].join('\n'));
    }

    return [
        '# Generated by Quantum. Edits are overwritten whenever a domain changes.',
        'http:',
        MIDDLEWARE,
        '  routers:' + (routers.length === 0 ? ' {}' : ''),
        ...routers,
        '  services:' + (services.length === 0 ? ' {}' : ''),
        ...services,
        ''
    ].join('\n');
};

export const writeUpstreamConfig = async (): Promise<void> => {
    if(!config.ingress.enabled) return;

    const domains = await Domain.find({ where: { target: DomainTarget.Upstream }, order: { id: 'ASC' } });
    const routes = domains
        .filter((domain): domain is Domain & { upstreamUrl: string } =>
            domain.upstreamUrl !== null && isRuleSafeHost(domain.host))
        .map((domain) => ({
            id: domain.id,
            host: domain.host,
            upstreamUrl: domain.upstreamUrl,
            tls: domain.tls
        }));

    const directory = config.ingress.dynamicDir;
    const target = path.join(directory, FILE_NAME);
    const staging = `${target}.tmp`;

    try{
        await mkdir(directory, { recursive: true });
        await writeFile(staging, renderUpstreamConfig(routes), 'utf8');
        await rename(staging, target);
        logger.info(`published ${routes.length} upstream ${routes.length === 1 ? 'route' : 'routes'}`,
            { scope: 'domain.ingress' });
    }catch(error){
        logger.error('could not publish the upstream routes', error, { scope: 'domain.ingress' });
    }
};
