import { mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import Domain from '../models/Domain';
import { DomainTarget } from '@quantum/contracts/modules/domain/domain';
import { config } from '@/shared/config';
import { logger } from '@/shared/utils/Logger';

const FILE_NAME = 'upstreams.yml';

/** Router and service names have to be stable and unique; the row id is both. */
const routerName = (domainId: number): string => `upstream-${domainId}`;

const quote = (value: string): string => JSON.stringify(value);

/**
 * `JSON.stringify` escapes quotes and backslashes but not backticks, and the proxy's rule
 * expression delimits values with backticks — so a host carrying one would close the
 * matcher and let whatever follows be read as more rule. Rows are validated on the way
 * in; this is the second gate, for anything already stored.
 */
export const isRuleSafeHost = (host: string): boolean => /^[a-z0-9*.-]+$/i.test(host);

interface UpstreamRoute{
    id: number;
    host: string;
    upstreamUrl: string;
    tls: boolean;
}

/**
 * The one middleware both providers share. Defined here rather than repeated as labels on
 * every container, and referenced across providers as `to-https@file` — so a plain request
 * to a TLS host is redirected by its own router instead of by the entrypoint.
 */
const MIDDLEWARE = [
    '  middlewares:',
    '    to-https:',
    '      redirectScheme:',
    '        scheme: https',
    '        permanent: true',
    // The panel's own api is served under /api on the panel host, and answers at the root
    // of its own routes — so the prefix is removed on the way through.
    '    strip-api:',
    '      stripPrefix:',
    '        prefixes: ["/api"]'
].join('\n');

export const renderUpstreamConfig = (routes: UpstreamRoute[]): string => {
    const routers: string[] = [];
    const services: string[] = [];

    for(const route of routes){
        const name = routerName(route.id);

        routers.push([
            `    ${name}:`,
            `      rule: ${quote(`Host(\`${route.host}\`)`)}`,
            `      entryPoints: [${route.tls ? 'websecure' : 'web'}]`,
            `      service: ${name}`,
            ...(route.tls ? ['      tls:', '        certResolver: le'] : [])
        ].join('\n'));

        /*
         * A TLS host also answers on plain HTTP, with a router that redirects. Without it
         * the host would simply 404 on port 80 — and port 80 is where a browser lands when
         * the reader types the name without a scheme.
         */
        if(route.tls){
            routers.push([
                `    ${name}-plain:`,
                `      rule: ${quote(`Host(\`${route.host}\`)`)}`,
                '      entryPoints: [web]',
                `      service: ${name}`,
                '      middlewares: [to-https]'
            ].join('\n'));
        }

        services.push([
            `    ${name}:`,
            '      loadBalancer:',
            '        servers:',
            `          - url: ${quote(route.upstreamUrl)}`
        ].join('\n'));
    }

    return [
        '# Generated by Quantum. Edits are overwritten whenever a domain changes.',
        'http:',
        MIDDLEWARE,
        // Empty maps rather than a missing key: the proxy watches this file, and removing
        // the last route has to take its router away with it.
        '  routers:' + (routers.length === 0 ? ' {}' : ''),
        ...routers,
        '  services:' + (services.length === 0 ? ' {}' : ''),
        ...services,
        ''
    ].join('\n');
};

/**
 * Publishes the routes that cannot be expressed as container labels.
 *
 * A domain pointing at a repository is routed by labels on that repository's own
 * container, which the proxy discovers through Docker. Anything else has no container to
 * label, so it is written here instead and picked up by the proxy's file provider — the
 * two mechanisms cover different targets and never describe the same route twice.
 */
export const writeUpstreamConfig = async (): Promise<void> => {
    if(!config.ingress.enabled) return;

    const domains = await Domain.find({ where: { target: DomainTarget.Upstream }, order: { id: 'ASC' } });
    const routes = domains
        .filter((domain): domain is Domain & { upstreamUrl: string } =>
            domain.upstreamUrl !== null && isRuleSafeHost(domain.host))
        .map((domain) => ({
            id: domain.id,
            host: domain.host,
            upstreamUrl: domain.upstreamUrl,
            tls: domain.tls
        }));

    const directory = config.ingress.dynamicDir;
    const target = path.join(directory, FILE_NAME);
    const staging = `${target}.tmp`;

    try{
        await mkdir(directory, { recursive: true });
        // Written aside and moved into place: the proxy watches this directory and would
        // otherwise reload a half-written document.
        await writeFile(staging, renderUpstreamConfig(routes), 'utf8');
        await rename(staging, target);
        logger.info(`published ${routes.length} upstream ${routes.length === 1 ? 'route' : 'routes'}`,
            { scope: 'domain.ingress' });
    }catch(error){
        logger.error('could not publish the upstream routes', error, { scope: 'domain.ingress' });
    }
};
