import { mkdir, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import Domain from '../models/Domain';
import { DomainTarget } from '@quantum/contracts/modules/domain/domain';
import { config } from '@/shared/config';
import { logger } from '@/shared/utils/Logger';

const FILE_NAME = 'upstreams.yml';

/** Router and service names have to be stable and unique; the row id is both. */
const routerName = (domainId: number): string => `upstream-${domainId}`;

const quote = (value: string): string => JSON.stringify(value);

/**
 * `JSON.stringify` escapes quotes and backslashes but not backticks, and the proxy's rule
 * expression delimits values with backticks — so a host carrying one would close the
 * matcher and let whatever follows be read as more rule. Rows are validated on the way
 * in; this is the second gate, for anything already stored.
 */
export const isRuleSafeHost = (host: string): boolean => /^[a-z0-9*.-]+$/i.test(host);

interface UpstreamRoute{
    id: number;
    host: string;
    upstreamUrl: string;
    tls: boolean;
}

export const renderUpstreamConfig = (routes: UpstreamRoute[]): string => {
    if(routes.length === 0){
        // An empty document rather than no file: the proxy watches this path, and deleting
        // the last route has to take its router away with it.
        return 'http:\n  routers: {}\n  services: {}\n';
    }

    const routers = routes.map((route) => {
        const lines = [
            `    ${routerName(route.id)}:`,
            `      rule: ${quote(`Host(\`${route.host}\`)`)}`,
            `      entryPoints: [${route.tls ? 'websecure' : 'web'}]`,
            `      service: ${routerName(route.id)}`
        ];
        if(route.tls) lines.push('      tls:', '        certResolver: le');
        return lines.join('\n');
    });

    const services = routes.map((route) => [
        `    ${routerName(route.id)}:`,
        '      loadBalancer:',
        '        servers:',
        `          - url: ${quote(route.upstreamUrl)}`
    ].join('\n'));

    return [
        '# Generated by Quantum. Edits are overwritten whenever a domain changes.',
        'http:',
        '  routers:',
        ...routers,
        '  services:',
        ...services,
        ''
    ].join('\n');
};

/**
 * Publishes the routes that cannot be expressed as container labels.
 *
 * A domain pointing at a repository is routed by labels on that repository's own
 * container, which the proxy discovers through Docker. Anything else has no container to
 * label, so it is written here instead and picked up by the proxy's file provider — the
 * two mechanisms cover different targets and never describe the same route twice.
 */
export const writeUpstreamConfig = async (): Promise<void> => {
    if(!config.ingress.enabled) return;

    const domains = await Domain.find({ where: { target: DomainTarget.Upstream }, order: { id: 'ASC' } });
    const routes = domains
        .filter((domain): domain is Domain & { upstreamUrl: string } =>
            domain.upstreamUrl !== null && isRuleSafeHost(domain.host))
        .map((domain) => ({
            id: domain.id,
            host: domain.host,
            upstreamUrl: domain.upstreamUrl,
            tls: domain.tls
        }));

    const directory = config.ingress.dynamicDir;
    const target = path.join(directory, FILE_NAME);
    const staging = `${target}.tmp`;

    try{
        await mkdir(directory, { recursive: true });
        // Written aside and moved into place: the proxy watches this directory and would
        // otherwise reload a half-written document.
        await writeFile(staging, renderUpstreamConfig(routes), 'utf8');
        await rename(staging, target);
        logger.info(`published ${routes.length} upstream ${routes.length === 1 ? 'route' : 'routes'}`,
            { scope: 'domain.ingress' });
    }catch(error){
        logger.error('could not publish the upstream routes', error, { scope: 'domain.ingress' });
    }
};
