import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { useApp } from '@tests/harness';
import { request, expectError } from '@tests/request';
import { seed } from '@tests/Seed';
import { metricRoutes } from '@quantum/contracts/modules/metric/routes';
import { UserRole } from '@quantum/contracts/modules/user/domain';
import Metric from '../models/Metric';
import { config } from '@/shared/config';
import type { DeepPartial } from 'typeorm';

const ctx = useApp();

let repositorySequence = 0;

const repositoryTable = (): string => {
    return config.databaseSchema === undefined ? 'repository' : `"${config.databaseSchema}".repository`;
};

const seedRepository = async (organizationId: number, userId: number, projectId: number): Promise<number> => {
    repositorySequence += 1;
    const rows: Array<{ id: number }> = await ctx.dataSource.query(
        `INSERT INTO ${repositoryTable()} (name, alias, url, "userId", "projectId", "organizationId")
         VALUES ($1, $2, $3, $4, $5, $6) RETURNING id`,
        [`repo-${repositorySequence}`, `repo-alias-${repositorySequence}`, `https://github.test/repo-${repositorySequence}`, userId, projectId, organizationId]
    );
    return rows[0].id;
};

const seedMetric = async (attributes: DeepPartial<Metric>): Promise<Metric> => {
    return Object.assign(Metric.create(), {
        cpuPercent: 12.5,
        memUsage: 1024,
        memLimit: 4096,
        memPercent: 25,
        netRx: 100,
        netTx: 50,
        blkRead: 0,
        blkWrite: 0,
        pids: 3,
        ts: new Date()
    }, attributes).save();
};

describe('metric', () => {
    let createdRepositoryTable = false;

    beforeAll(async () => {
        const rows: Array<{ present: string | null }> = await ctx.dataSource.query(`SELECT to_regclass('${repositoryTable()}') AS present`);
        if(rows[0].present === null){
            await ctx.dataSource.query(`
                CREATE TABLE ${repositoryTable()} (
                    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    name varchar NOT NULL,
                    alias varchar NOT NULL,
                    url varchar NOT NULL,
                    "userId" integer NOT NULL,
                    "projectId" integer NOT NULL,
                    "organizationId" integer
                )
            `);
            createdRepositoryTable = true;
        }
    });

    afterAll(async () => {
        if(createdRepositoryTable){
            await ctx.dataSource.query(`DROP TABLE ${repositoryTable()}`);
        }
    });

    it('rejects unauthenticated requests', async () => {
        const res = await request(ctx.app, metricRoutes.byRepository, { params: { repositoryId: 1 } });

        expectError(res, 401, 'Authentication::Unauthorized');
    });

    it('returns repository metrics for a member of the owning organization', async () => {
        const { user, org } = await seed.orgContext();
        const repositoryId = await seedRepository(org.id, user.id, 1);
        await seedMetric({ organizationId: org.id, repositoryId });
        await seedMetric({ organizationId: org.id, repositoryId });

        const res = await request(ctx.app, metricRoutes.byRepository, {
            as: user.id,
            params: { repositoryId }
        });

        expect(res.status).toBe(200);
        expect(res.data()).toHaveLength(2);
        for(const metric of res.data()){
            expect(metric.repositoryId).toBe(repositoryId);
            expect(metric.cpuPercent).toBe(12.5);
        }
    });

    it('forbids repository metrics for a non-member organization', async () => {
        const owner = await seed.orgContext();
        const outsider = await seed.orgContext();
        const repositoryId = await seedRepository(owner.org.id, owner.user.id, 1);
        await seedMetric({ organizationId: owner.org.id, repositoryId });

        const res = await request(ctx.app, metricRoutes.byRepository, {
            as: outsider.user.id,
            params: { repositoryId }
        });

        expectError(res, 403, 'Metric::Forbidden');
    });

    it('answers 404 for an unknown repository', async () => {
        const { user } = await seed.orgContext();

        const res = await request(ctx.app, metricRoutes.byRepository, {
            as: user.id,
            params: { repositoryId: 999999 }
        });

        expectError(res, 404, 'Metric::NotFound');
    });

    it('lets a platform admin read metrics of a foreign repository', async () => {
        const owner = await seed.orgContext();
        const admin = await seed.user(UserRole.Admin);
        const repositoryId = await seedRepository(owner.org.id, owner.user.id, 1);
        await seedMetric({ organizationId: owner.org.id, repositoryId });

        const res = await request(ctx.app, metricRoutes.byRepository, {
            as: admin.id,
            params: { repositoryId }
        });

        expect(res.status).toBe(200);
        expect(res.data()).toHaveLength(1);
    });

    it('applies the limit and minutes window', async () => {
        const { user, org } = await seed.orgContext();
        const repositoryId = await seedRepository(org.id, user.id, 1);
        await seedMetric({ organizationId: org.id, repositoryId });
        await seedMetric({ organizationId: org.id, repositoryId });
        await seedMetric({ organizationId: org.id, repositoryId, ts: new Date(Date.now() - 120 * 60 * 1000) });

        const limited = await request(ctx.app, metricRoutes.byRepository, {
            as: user.id,
            params: { repositoryId },
            query: { limit: 1 }
        });
        expect(limited.status).toBe(200);
        expect(limited.data()).toHaveLength(1);

        const windowed = await request(ctx.app, metricRoutes.byRepository, {
            as: user.id,
            params: { repositoryId },
            query: { minutes: 60 }
        });
        expect(windowed.status).toBe(200);
        expect(windowed.data()).toHaveLength(2);
    });
});
