/***
 * Copyright (C) Rodolfo Herrera Hernandez. All rights reserved.
 * Licensed under the MIT license. See LICENSE file in the project root
 * for full license information.
 *
 * =+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
 *
 * For related information - https://github.com/rodyherrera/Quantum/
 *
 * All your applications, just in one place.
 *
 * =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
****/

import Database from '@models/database';
import DockerContainer from '@models/docker/container';
import HandlerFactory from '@controllers/common/handlerFactory';
import RuntimeError from '@utilities/runtimeError';
import { catchAsync } from '@utilities/helpers';
import { enqueueDatabaseJob } from '@services/orchestrator';
import { resolveProjectOr403 } from '@middlewares/tenancy';
import { IRequest } from '@typings/controllers/common';
import { Response, NextFunction } from 'express';

/**
 * Managed databases are project-scoped (transitively tenant-scoped, as with
 * environments/alert channels). The factory handles list/get/delete tenant
 * matching; create + lifecycle actions are custom because they generate
 * credentials and dispatch orchestrator jobs.
 *
 * SECURITY: credentialsEnc + connectionStringEnc are `select:false` on the model,
 * so factory reads never include them. The decrypted connection string is exposed
 * ONLY by the explicit /:id/connection-string endpoint (deploy permission).
 */
const DatabaseFactory = new HandlerFactory({
    model: Database,
    scope: { field: 'organization' },
    fields: ['name']
});

export const getDatabases = DatabaseFactory.getAll();
export const getDatabase = DatabaseFactory.getOne();

/**
 * Mongo filter restricting a query to databases the caller can reach: all of them
 * for a platform admin, otherwise those under the caller's accessible projects.
 * Used by the /:id lifecycle endpoints (backup/restore/connection-string), which
 * key off a database id rather than a :projectId.
 */
const reachableScope = (req: IRequest): Record<string, unknown> =>
    req.tenant?.isPlatformAdmin ? {} : { project: { $in: req.tenant?.projectIds || [] } };

/** Lookup a database by id within the caller's reachable scope, or 404. */
const findReachableDatabase = async (req: IRequest, select?: string) => {
    const query = Database.findOne({ _id: req.params.id, ...reachableScope(req) });
    return select ? query.select(select) : query;
};

/**
 * Create a managed database under :projectId and enqueue its provisioning. Returns
 * 202 (provisioning happens asynchronously in the orchestrator). The project/user
 * are stamped from verified context, never the body; credentials are generated by
 * the provisioner, never accepted from the client.
 */
export const createDatabase = catchAsync(async (req: IRequest, res: Response, next: NextFunction): Promise<void> => {
    const project = await resolveProjectOr403(req, next, 'Database');
    if(!project) return;

    const userId = (req.user as any)?._id;
    const database = await Database.create({
        name: req.body.name,
        engine: req.body.engine,
        version: req.body.version,
        organization: project.organization,
        project: project._id,
        user: userId,
        status: 'pending'
    });

    await enqueueDatabaseJob('db:provision', database._id.toString(), {
        userId: userId?.toString(),
        projectId: project._id.toString()
    });

    res.status(202).json({ status: 'success', data: database });
});

/** Enqueue a backup for a database the caller can reach (deploy permission). */
export const backupDatabase = catchAsync(async (req: IRequest, res: Response, next: NextFunction): Promise<void> => {
    const database = await findReachableDatabase(req);
    if(!database){
        return next(new RuntimeError('Database::NotFound', 404));
    }
    const job = await enqueueDatabaseJob('db:backup', database._id.toString(), {
        userId: (req.user as any)?._id?.toString(),
        projectId: database.project?.toString()
    });
    res.status(202).json({ status: 'success', data: { jobId: job._id } });
});

/** Enqueue a restore from a prior backup id (deploy permission). */
export const restoreDatabase = catchAsync(async (req: IRequest, res: Response, next: NextFunction): Promise<void> => {
    const backupId = req.body?.backupId;
    if(!backupId){
        return next(new RuntimeError('Database::Restore::BackupIdRequired', 400));
    }
    const database = await findReachableDatabase(req);
    if(!database){
        return next(new RuntimeError('Database::NotFound', 404));
    }
    const job = await enqueueDatabaseJob('db:restore', database._id.toString(), {
        userId: (req.user as any)?._id?.toString(),
        projectId: database.project?.toString(),
        backupId
    });
    res.status(202).json({ status: 'success', data: { jobId: job._id } });
});

/**
 * Return the DECRYPTED connection string for a database (deploy permission). This
 * is the ONLY path that reveals the secret — credentialsEnc/connectionStringEnc are
 * select:false everywhere else, so list/get never leak it.
 */
export const getConnectionString = catchAsync(async (req: IRequest, res: Response, next: NextFunction): Promise<void> => {
    const database = await findReachableDatabase(req, '+connectionStringEnc');
    if(!database){
        return next(new RuntimeError('Database::NotFound', 404));
    }
    const connectionString = database.getConnectionString();
    if(!connectionString){
        return next(new RuntimeError('Database::ConnectionString::Unavailable', 409));
    }
    res.status(200).json({ status: 'success', data: { connectionString } });
});

/**
 * Delete a database: stop+remove its engine container, then delete the doc
 * (tenant-scoped match via the factory). deploy permission required.
 */
export const deleteDatabase = DatabaseFactory.deleteOne({
    middlewares: {
        pre: [async (req: IRequest) => {
            // Tear down the runtime container BEFORE the doc is removed. The factory
            // re-applies the tenant scope on the actual delete, so this lookup is
            // only to find the container to clean up; failures are non-fatal.
            const database = await Database.findOne({ _id: req.params.id });
            if(database?.container){
                const container = await DockerContainer.findById(database.container);
                if(container){
                    // findOneAndDelete cascade removes the container + network + volumes.
                    await DockerContainer.findOneAndDelete({ _id: container._id });
                }
            }
            return {};
        }]
    }
});

export default {
    getDatabases,
    getDatabase,
    createDatabase,
    backupDatabase,
    restoreDatabase,
    getConnectionString,
    deleteDatabase
};
